language: generic
sudo: false # use the container-based Travis-CI infrastructure
install:
- npm install -g nw-global-build
- gem install fpm # nw-global-build uses this to build Linux packages (.deb and .rpm)
addons:
  apt:
    packages:
      - nsis
script: nw-global-build build
