init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node 6
  - npm install
  - npm install -g nw-global-build
test_script:
  - node --version
  - npm --version
  - nw-global-build build win
build: off
