init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node 6
  - npm install
  - npm install -g nw-global-build
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%
  - echo %PATH%
test_script:
  - node --version
  - npm --version
  - nw-global-build build win
build: off
